[MISC][RL] Update error handling in pipeline script

diff --git a/.github/workflows/trigger-gitlab-pipeline.yml b/.github/workflows/trigger-gitlab-pipeline.yml
--- a/.github/workflows/trigger-gitlab-pipeline.yml
+++ b/.github/workflows/trigger-gitlab-pipeline.yml
@@ -66,7 +66,7 @@ jobs:
           GITLAB_PROJECT_ID: ${{ vars.GITLAB_PROJECT_ID }}
           SLEEP_DURATION_MINUTES: 20
           CHECK_INTERVAL_MINUTES: 5
-          MAX_RETRY_ATTEMPTS: 5
+          MAX_RETRY_ATTEMPTS: 6
           DOWNSTREAM_PIPELINE_NAME: library
           DOWNSTREAM_JOB_NAME: build-dist-job
         run: |
@@ -80,19 +80,31 @@ jobs:
           do
             echo "Attempt: $num_attempts"
 
-            downstream_pipeline_id=$(curl -sS --request GET --header "PRIVATE-TOKEN: $GITLAB_PAT" \
-              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$PIPELINE_ID/bridges" \
-              | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_PIPELINE_NAME"'")) ]' | jq -r '.[].downstream_pipeline.id')
+            set +e
+
+            pipeline_res=$(curl -sSf --request GET --header "PRIVATE-TOKEN: $GITLAB_PAT" \
+              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$PIPELINE_ID/bridges")
+            if [[ $? -ne 0 ]]; then
+              echo "Failed to fetch downstream pipelines"
+              break
+            fi
+
+            downstream_pipeline_id=$(echo "$pipeline_res" | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_PIPELINE_NAME"'")) ]' | jq -r '.[].downstream_pipeline.id')
             echo "($DOWNSTREAM_PIPELINE_NAME) Downstream pipeline id: $downstream_pipeline_id"
 
-            job_status=$(curl -sS --header "PRIVATE-TOKEN: $GITLAB_PAT" \
-              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$downstream_pipeline_id/jobs" \
-              | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_JOB_NAME"'")) ]' | jq -r '.[].status')
+            job_status_res=$(curl -sSf --header "PRIVATE-TOKEN: $GITLAB_PAT" \
+              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$downstream_pipeline_id/jobs")
+            if [[ $? -ne 0 ]]; then
+              echo "Failed to fetch jobs for downstream pipeline"
+              break
+            fi
+
+            job_status=$(echo "$job_status_res" | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_JOB_NAME"'")) ]' | jq -r '.[].status')
             echo "($DOWNSTREAM_JOB_NAME) Job status: $job_status"
 
-            if [[ $job_status == "running" ]]; then
-              num_attempts=$((num_attempts+1))
-            fi
+            set -e
+
+            num_attempts=$((num_attempts+1))
 
             if [[ $num_attempts -lt $MAX_RETRY_ATTEMPTS ]]; then
               sleep $(($CHECK_INTERVAL_MINUTES*60))
@@ -100,6 +112,8 @@ jobs:
           done
 
           [[ $num_attempts -gt $MAX_RETRY_ATTEMPTS ]] && echo "Number of retries exceeded, please head to the GitLab job to check what happened" && exit 1
+
+          [[ $job_status == "" ]] && echo "Couldn't get GitLab job status, please check if the GITLAB_PAT has sufficient permissions." && exit 1
 
           [[ $job_status == "canceled" ]] && echo "GitLab job was cancelled"
 
