test

diff --git a/.github/workflows/trigger-gitlab-pipeline.yml b/.github/workflows/trigger-gitlab-pipeline.yml
--- a/.github/workflows/trigger-gitlab-pipeline.yml
+++ b/.github/workflows/trigger-gitlab-pipeline.yml
@@ -80,14 +80,24 @@ jobs:
           do
             echo "Attempt: $num_attempts"
 
-            downstream_pipeline_id=$(curl -sSf --request GET --header "PRIVATE-TOKEN: $GITLAB_PAT" \
-              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$PIPELINE_ID/bridges" \
-              | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_PIPELINE_NAME"'")) ]' | jq -r '.[].downstream_pipeline.id')
+            pipeline_res=$(curl -sSf --request GET --header "PRIVATE-TOKEN: $GITLAB_PAT" \
+              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$PIPELINE_ID/bridges")
+            if [[ $? -ne 0 ]]; then
+              echo "Failed to fetch downstream pipelines"
+              break
+            fi
+
+            downstream_pipeline_id=$(echo "$pipeline_res" | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_PIPELINE_NAME"'")) ]' | jq -r '.[].downstream_pipeline.id')
             echo "($DOWNSTREAM_PIPELINE_NAME) Downstream pipeline id: $downstream_pipeline_id"
 
-            job_status=$(curl -sSf --header "PRIVATE-TOKEN: $GITLAB_PAT" \
-              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$downstream_pipeline_id/jobs" \
-              | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_JOB_NAME"'")) ]' | jq -r '.[].status')
+            job_status_res=$(curl -sSf --header "PRIVATE-TOKEN: $GITLAB_PAT" \
+              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipelines/$downstream_pipeline_id/jobs")
+            if [[ $? -ne 0 ]]; then
+              echo "Failed to fetch jobs for downstream pipeline"
+              break
+            fi
+
+            job_status=$(echo "$job_status_res" | jq -r '[ .[] | select( .name | contains("'"$DOWNSTREAM_JOB_NAME"'")) ]' | jq -r '.[].status')
             echo "($DOWNSTREAM_JOB_NAME) Job status: $job_status"
 
             num_attempts=$((num_attempts+1))
@@ -98,6 +108,8 @@ jobs:
           done
 
           [[ $num_attempts -gt $MAX_RETRY_ATTEMPTS ]] && echo "Number of retries exceeded, please head to the GitLab job to check what happened" && exit 1
+
+          [[ $job_status == "" ]] && echo "Couldn't get GitLab job status, please check if the GITLAB_PAT has sufficient permissions." && exit 1
 
           [[ $job_status == "canceled" ]] && echo "GitLab job was cancelled"
 
